# Generated by Django 4.1 on 2022-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_familiar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='nombre',
            new_name='name',
        ),
    ]
